---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 746492705711198208-t7jBJW6oaf0ayeB76RRRwu7q0f38iXT
:access_token_secret: jmIarVMWtj4NGeoTNNlubDJD5cxx15QddCyumSW6K7kVg
